import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DiveState,INPUTS,NODES,RECEPTORS,MEMORY} from '../lib/dive-state.ts';
const idle={forward:0,strafe:0,jump:false,sprint:false};
function walk(game,seconds,extra={}){for(let i=0;i<Math.ceil(seconds*60);i++)game.tick(1/60,{...idle,...extra});}
function position(game,p){game.player.x=p.x;game.player.z=p.z;game.player.y=0;game.vy=0;}
function openAxon(game){game.start();for(const p of INPUTS){position(game,p);assert.equal(game.interact(),true);}}
function openSynapse(game){openAxon(game);walk(game,1.3);for(const z of NODES){position(game,{x:0,z});assert.equal(game.interact(),true);walk(game,1.3);}}
test('threshold gate needs all inputs and repeated interaction gives no extra points',()=>{const g=new DiveState();g.start();position(g,{x:0,z:-8});walk(g,1,{forward:1});assert.equal(g.player.z,-9);for(const p of INPUTS){position(g,p);g.interact();const score=g.score;g.interact();assert.equal(g.score,score);}assert.equal(g.potential(),-55);assert.equal(g.stage,'axon');assert.equal(g.score,400);});
test('nodes are ordered and refractory period prevents immediate reactivation',()=>{const g=new DiveState();openAxon(g);position(g,{x:0,z:NODES[1]});assert.equal(g.interact(),false);position(g,{x:0,z:NODES[0]});assert.equal(g.interact(),false);walk(g,1.3);assert.equal(g.interact(),true);position(g,{x:0,z:NODES[1]});assert.equal(g.interact(),false);walk(g,1.3);assert.equal(g.interact(),true);});
test('walking into gap falls and returns to current checkpoint without losing learned inputs',()=>{const g=new DiveState();openAxon(g);walk(g,1.3);position(g,{x:0,z:NODES[0]});g.interact();position(g,{x:0,z:-26});walk(g,2,{forward:1});assert.equal(g.falls,1);assert.equal(g.collected.size,3);assert.equal(g.nodes,1);assert.equal(g.stage,'axon');assert.ok(g.player.z>-27);});
test('jump can cross gap without fall and land on platform',()=>{const g=new DiveState();openAxon(g);position(g,{x:0,z:-25.8});g.tick(1/60,{...idle,jump:true,forward:1});walk(g,.7,{forward:1});walk(g,.4);assert.equal(g.falls,0);assert.ok(g.player.z< -28.4);assert.equal(g.player.y,0);});
test('pause freezes movement, time, and interaction',()=>{const g=new DiveState();g.start();position(g,INPUTS[0]);g.pause();const before={...g.player};walk(g,4,{forward:1});assert.deepEqual(g.player,before);assert.equal(g.elapsed,0);assert.equal(g.interact(),false);});
test('chemical transmission requires calcium, release and matching receptor',()=>{const g=new DiveState(2);openSynapse(g);position(g,{x:0,z:-71});assert.equal(g.interact(),false);position(g,{x:-3,z:-64});g.interact();position(g,{x:0,z:-71});g.interact();assert.equal(g.released,true);position(g,RECEPTORS[0]);g.interact();assert.equal(g.phase,'playing');assert.equal(g.wrong,1);position(g,RECEPTORS[2]);g.interact();assert.equal(g.phase,'complete');const score=g.score;assert.equal(g.interact(),false);assert.equal(g.score,score);assert.equal(g.score,1300);});

test('interactions cannot reach up through the floor while falling',()=>{const g=new DiveState();g.start();position(g,INPUTS[0]);g.player.y=-1;assert.equal(g.nearby(),null);assert.equal(g.interact(),false);assert.equal(g.score,0);});
test('overlapping receptor ranges select the nearest receptor',()=>{const g=new DiveState(2);openSynapse(g);position(g,{x:-3,z:-64});g.interact();position(g,{x:0,z:-71});g.interact();position(g,{x:2.3,z:-86});assert.equal(g.nearby().id,'receptor-2');g.interact();assert.equal(g.phase,'complete');});
test('memory capsule explains the concept visibly and cannot be scored twice',()=>{const g=new DiveState();g.start();position(g,MEMORY[0]);assert.equal(g.interact(),true);assert.ok(g.snapshot().message.includes(MEMORY[0].text));assert.equal(g.score,50);assert.equal(g.interact(),false);assert.equal(g.score,50);});
