'use client';
import {useEffect,useRef,useState} from 'react';
import {DiveState,type DiveSnapshot} from '@/lib/dive-state';
import type {DiveEngine} from '@/lib/dive-engine';
import './dive.css';
const STAGES={input:{no:'01',title:'樹状突起の庭',en:'DENDRITE GARDEN'},axon:{no:'02',title:'軸索の回廊',en:'AXON CORRIDOR'},synapse:{no:'03',title:'シナプスの岸',en:'SYNAPTIC SHORE'}};
const timeText=(s:number)=>Math.floor(s/60).toString().padStart(2,'0')+' '+Math.floor(s%60).toString().padStart(2,'0');
type RecordData={runs:number;best:number};
export default function DiveGame(){
 const host=useRef<HTMLDivElement>(null),engine=useRef<DiveEngine|null>(null),saved=useRef(false);
 const [view,setView]=useState<DiveSnapshot>(()=>new DiveState().snapshot());
 const [ready,setReady]=useState(false),[modelStatus,setModelStatus]=useState('loading'),[error,setError]=useState('');
 const [sound,setSound]=useState(false),[runKey,setRunKey]=useState(0),[record,setRecord]=useState<RecordData>({runs:0,best:0}),[saveOk,setSaveOk]=useState(true);
 const [notes,setNotes]=useState(false);
 const pressedAt=useRef<Record<string,number>>({});
 useEffect(()=>{
  let canceled=false;saved.current=false;setReady(false);setError('');setModelStatus('loading');
  void import('@/lib/dive-engine').then(({DiveEngine})=>{
   if(canceled||!host.current)return;
   try{engine.current=new DiveEngine(host.current,setView,setError,ok=>setModelStatus(ok?'loaded':'failed'));setView(engine.current.model.snapshot());setReady(true);}catch{setError('このブラウザーでは3D描画を開始できなかった。WebGLが使えるブラウザーで開くか、2D版から遊べるよ。');}
  }).catch(()=>setError('3Dの読み込みに失敗した。もう一度読み込んでみてね。'));
  return()=>{canceled=true;engine.current?.dispose();engine.current=null;};
 },[runKey]);
 useEffect(()=>{try{const raw=JSON.parse(localStorage.getItem('neurolab-dive-v1')||'{}');setRecord({runs:Number.isFinite(raw.runs)?Math.max(0,Math.floor(raw.runs)):0,best:Number.isFinite(raw.best)?Math.max(0,Math.floor(raw.best)):0});}catch{setSaveOk(false);}},[]);
 useEffect(()=>{
  if(view.phase!=='complete'||saved.current)return;saved.current=true;
  setRecord(previous=>{const next={runs:previous.runs+1,best:Math.max(previous.best,view.score)};try{localStorage.setItem('neurolab-dive-v1',JSON.stringify(next));}catch{setSaveOk(false);}return next;});
 },[view.phase,view.score]);
 useEffect(()=>{if(engine.current)engine.current.sound=sound;},[sound,ready]);
 useEffect(()=>{
  if(!ready)return;
  type MC={registerTool:(tool:Record<string,unknown>,options:{signal:AbortSignal})=>void|Promise<void>};
  const context=(document as Document&{modelContext?:MC}).modelContext;if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const state=()=>{const e=engine.current;if(!e)throw Error('Game is loading');return e.model.snapshot();};
  const settle=async()=>{await new Promise<void>(r=>requestAnimationFrame(()=>r()));return state();};
  const register=(tool:Record<string,unknown>)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'get_neuro_dive_state',description:'Read the first-person game phase, visible objective, player position, nearby interaction and score.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:state});
  register({name:'control_neuro_dive',description:'Use the same game actions as the visible controls. Start, pause, resume, jump, or interact with a nearby object. Does not teleport or bypass game rules.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['start','pause','resume','jump','interact']}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const action=(input as {action?:string})?.action;const e=engine.current;if(!e)throw Error('Game is loading');if(!['start','pause','resume','jump','interact'].includes(action||''))throw Error('Invalid action');if(action==='start'){if(e.model.phase!=='ready')throw Error('Game has already started');e.start();}if(action==='pause')e.pause();if(action==='resume')e.resume();if(action==='jump')e.jump();if(action==='interact')e.interact();return settle();}});
  register({name:'move_neuro_dive',description:'Walk using normal first-person movement and collisions for up to two seconds. Forward follows camera heading, left/right strafe. Set jump true to press jump and movement together, using the same physics as Space plus WASD.',inputSchema:{type:'object',properties:{direction:{type:'string',enum:['forward','backward','left','right']},seconds:{type:'number',minimum:.05,maximum:2},jump:{type:'boolean'}},required:['direction','seconds'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const value=input as {direction:string;seconds:number;jump?:boolean};if(!engine.current)throw Error('Game is loading');return engine.current.move(value?.direction,value?.seconds,value?.jump);}});
  register({name:'turn_neuro_dive',description:'Turn the first-person view horizontally by up to 90 degrees. Positive values turn left, negative values turn right.',inputSchema:{type:'object',properties:{degrees:{type:'number',minimum:-90,maximum:90}},required:['degrees'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const degree=(input as {degrees:number})?.degrees;if(!Number.isFinite(degree)||Math.abs(degree)>90)throw Error('Degrees must be between -90 and 90');if(!engine.current||engine.current.model.phase!=='playing')throw Error('Start or resume the game first');engine.current.turn(degree);return settle();}});
  return()=>lifecycle.abort();
 },[ready,runKey]);
 const phase=view.phase,active=phase==='playing',stage=STAGES[view.stage];
 function down(e:React.PointerEvent<HTMLButtonElement>,code:string){if(!active)return;e.currentTarget.setPointerCapture(e.pointerId);pressedAt.current[code]=performance.now();engine.current?.keys.add(code);}
 function up(code:string,direction:string){engine.current?.keys.delete(code);if(active&&performance.now()-(pressedAt.current[code]||0)<180)engine.current?.step(direction);delete pressedAt.current[code];}
 function showNotes(){engine.current?.pause();setNotes(true);}
 return <div className={'dive-shell '+(active?'is-active':'')}>
 <div className="dive-canvas" ref={host}/>
 <div className="dive-vignette" aria-hidden="true"/>
 <header className="dive-header"><a href="/" className="dive-brand"><span>✳</span><b>NEURO DIVE</b><small>BY NEUROLAB</small></a><div className="dive-header-actions"><button onClick={()=>setSound(v=>!v)} aria-label="効果音" aria-pressed={sound}>{sound?'♪ ON':'♪ OFF'}</button><button onClick={showNotes}>探索ノート</button>{active&&<button onClick={()=>engine.current?.pause()} aria-label="一時停止">Ⅱ</button>}<a href="/" className="back-arcade">2D版へ ↗</a></div></header>
 {ready&&phase!=='ready'&&phase!=='complete'&&<><section className="dive-objective" aria-label="現在のミッション"><div className="dive-eyebrow"><span>CHAPTER {stage.no}</span><span>{stage.en}</span></div><h1>{stage.title}</h1><p>{view.target.description}</p><div className="objective-line"><span className="objective-marker">◇</span><strong>{view.target.label}</strong><span>{view.distance.toFixed(0)} m</span></div><div className="dive-checkpoints"><span className={view.stage==='input'?'current':'done'}>① 入力 {view.inputs} of 3</span><span className={view.stage==='axon'?'current':view.stage==='synapse'?'done':''}>② 伝導 {view.nodes} of 3</span><span className={view.stage==='synapse'?'current':''}>③ 接続</span></div></section><div className="dive-stats"><span>{timeText(view.elapsed)}<small>ELAPSED</small></span><span>{view.score}<small>KNOWLEDGE XP</small></span></div></>}
 {active&&<><div className="crosshair" aria-hidden="true"><i/><i/></div>
 <div className="dive-message" role="status" aria-live="polite">{view.message&&<p>{view.message}</p>}{view.nearby&&<button onClick={()=>engine.current?.interact()}><kbd>E</kbd> {view.nearby.label}</button>}</div>
 <div className="dive-bottom"><section className="potential-panel" aria-label="膜電位"><span className="dive-eyebrow">{view.stage==='input'?'MEMBRANE POTENTIAL':view.released?'CHEMICAL SIGNAL':'ELECTRICAL SIGNAL'}</span><div><strong>{view.released?view.receptor:view.stage==='input'?view.potential:'→'}</strong><span>{view.released?'の伝達物質':view.stage==='input'?'mV':'活動電位'}</span></div><div className="voltage-meter"><i style={{width:(view.stage==='input'?view.inputs/3*100:100)+'%'}}/></div><small>{view.stage==='input'?'発火の閾値 −55 mV':view.cooldown>0?'不応期 · '+view.cooldown.toFixed(1)+' 秒':view.released?'対応する受容体に結びつける':'強さは一定 · 全か無か'}</small></section>
 <div className="desktop-controls"><span><kbd>W A S D</kbd> 移動</span><span><kbd>SPACE</kbd> ジャンプ</span><span><kbd>E</kbd> 接続</span><span><kbd>ESC</kbd> 停止</span><button onClick={()=>engine.current?.captureMouse()}>マウス視点を有効に</button></div>
 <div className="dive-microfacts"><span>◇ {view.memories} of 3 記憶カプセル</span><span>世界の寸法と時間はゲーム用に拡大</span></div></div>
 <div className="touch-controls" aria-label="画面の移動コントローラー"><div className="direction-pad">{[{label:'前へ',icon:'↑',code:'KeyW',dir:'forward'},{label:'左へ',icon:'←',code:'KeyA',dir:'left'},{label:'後ろへ',icon:'↓',code:'KeyS',dir:'backward'},{label:'右へ',icon:'→',code:'KeyD',dir:'right'}].map(c=><button key={c.code} aria-label={c.label} className={c.dir} onPointerDown={e=>down(e,c.code)} onPointerUp={()=>up(c.code,c.dir)} onPointerCancel={()=>engine.current?.keys.delete(c.code)} onClick={e=>{if(e.detail===0)engine.current?.step(c.dir);}}>{c.icon}</button>)}</div><div className="touch-actions"><button onClick={()=>engine.current?.jump()} aria-label="ジャンプ">↑<small>JUMP</small></button><button onClick={()=>engine.current?.interact()} aria-label="近くの対象を操作">E<small>接続</small></button></div></div>
 </>}
 {(!ready||error)&&<section className="dive-overlay"><div className="dive-dialog"><p className="dive-eyebrow">NEURAL ENVIRONMENT</p><h1>{error?'3Dを読み込めなかった':'脳内の世界を構築中'}</h1><p>{error||'3Dモデルと神経の回廊を準備している。'}</p>{error&&<><button className="dive-primary" onClick={()=>setRunKey(k=>k+1)}>もう一度読み込む</button><a href="/">2Dゲームを開く ↗</a></>}</div></section>}
 {ready&&phase==='ready'&&!error&&<section className="dive-start"><div className="dive-start-copy"><p className="dive-eyebrow">A FIRST-PERSON JOURNEY THROUGH THE BRAIN</p><h1>ひとつの信号が、<br/>世界をつなぐ。</h1><p>樹状突起の庭から、シナプスの岸へ。<br/>自分の足で探索しながら、脳の仕組みを覚えよう。</p><div className="dive-start-tags"><span>一人称3D探索</span><span>3つのエリア</span><span>約5分</span></div><button className="dive-primary" onClick={()=>engine.current?.start(true)}>ダイブを開始 <span>→</span></button><p className="start-instructions"><kbd>WASD</kbd> 移動 <kbd>マウス</kbd> 視点 <kbd>E</kbd> 接続<br/>クリックでマウスを捕捉。Escで解除できる。<br/>ドラッグと画面のボタンでも操作できる。</p></div><div className="dive-atlas-caption"><i/><span>{modelStatus==='loaded'?'HUMAN REFERENCE ATLAS · 3D BRAIN':modelStatus==='failed'?'脳モデルを読み込めなかった。ステージは遊べる。':'人間の脳モデルを読み込み中'}<small>実際の解剖データによる脳モデル</small></span></div>{record.runs>0&&<div className="dive-record">BEST {record.best} XP · {record.runs} RUNS</div>}</section>}
 {ready&&phase==='paused'&&!notes&&!error&&<section className="dive-overlay"><div className="dive-dialog"><p className="dive-eyebrow">SIGNAL ON HOLD</p><h1>ひと休み。</h1><p>今の位置から、そのまま続けられる。<br/>視点の揺れと自動カメラ移動はオフ。</p><button className="dive-primary" onClick={()=>engine.current?.resume(true)}>探索に戻る <span>→</span></button><button className="dive-secondary" onClick={()=>engine.current?.resume(false)}>ドラッグ操作で戻る</button><button className="dive-secondary" onClick={()=>setNotes(true)}>学んだ仕組みを見る</button><a href="/">2D版に戻る ↗</a></div></section>}
 {phase==='complete'&&!notes&&<section className="dive-overlay"><div className="dive-dialog result-dialog"><p className="dive-eyebrow">CONNECTION COMPLETE</p><div className="dive-medal">✳</div><h1>届いた。<br/>次のニューロンへ。</h1><p>入力の統合、活動電位、化学シナプス。<br/>自分が通った道が、知識になった。</p><div className="dive-result-stats"><div><b>{view.score}</b><span>KNOWLEDGE XP</span></div><div><b>{timeText(view.elapsed)}</b><span>走破タイム</span></div><div><b>{view.memories} of 3</b><span>記憶カプセル</span></div></div><p className="result-learning">{view.fact}</p><button className="dive-primary" onClick={()=>setRunKey(k=>k+1)}>もう一度ダイブ <span>↻</span></button><button className="dive-secondary" onClick={()=>setNotes(true)}>探索ノートで振り返る</button><p className="dive-save-note">{saveOk?'クリア記録をこのブラウザーに保存した。':'このブラウザーでは記録を保存できなかった。'}</p></div></section>}
 {notes&&<section className="dive-overlay notes-overlay"><article className="dive-dialog notes-dialog"><p className="dive-eyebrow">FIELD NOTES & CREDITS</p><h1>さっきの体験は、<br/>何だったのか。</h1><dl><dt>① 入力を集める</dt><dd>樹状突起や細胞体で受けた入力が統合され、閾値を超えると活動電位が生じる。−70 mVと−55 mVは代表例で、細胞ごとに値は異なる。入力を拾う操作と永続するゲージはゲーム用の簡略化。</dd><dt>② 絞輪をつなぐ</dt><dd>軸索を包む髄鞘は絶縁に役立ち、間にあるランビエ絞輪で活動電位が再生される。これが跳躍伝導。床の切れ目を飛ぶのは移動の仕掛けで、生体の軸索に床や穴はない。不応期の時間は遊べる長さに拡大している。</dd><dt>③ 化学物質で橋渡し</dt><dd>典型的な化学シナプスでは、終末へのカルシウム流入が伝達物質の放出を引き起こす。伝達物質はすき間を拡散し、受容体に結びつく。形合わせは選択性を表す比喩で、分子の実際の形を再現したものではない。結合しても次の細胞が必ず発火するわけではない。</dd></dl><div className="dive-source-list"><a href="https://www.brainfacts.org/brain-anatomy-and-function/cells-and-circuits/2020/the-action-potential-the-brains-most-efficient-game-of-telephone-101220" target="_blank" rel="noreferrer">BrainFacts · 活動電位と跳躍伝導 ↗</a><a href="https://www.brainfacts.org/brain-anatomy-and-function/cells-and-circuits/2022/synapses-and-neurotransmission-113022" target="_blank" rel="noreferrer">BrainFacts · 化学シナプス ↗</a></div><div className="brain-credit"><strong>脳の3Dモデル</strong><p>Kristen Browne & Heidi Schlehlein (2023). <a href="https://doi.org/10.48539/HBM929.XKCL.339" target="_blank" rel="noreferrer">3D Reference Organ for Brain, Male v1.3</a>. HuBMAP Human Reference Atlas. Allen Human Reference Atlasのデータに由来する。</p><p><a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a>。表示の色、縮尺、位置、向きを変更し、描画時にメッシュを統合。原データが持つ左右の鏡映とサイズ調整を継承。ゲームの舞台は細胞の仕組みを拡大した創作空間。</p></div><button className="dive-primary" onClick={()=>setNotes(false)}>ノートを閉じる <span>×</span></button></article></section>}
 </div>;
}
